// Generated by EmberScript 0.0.11
void function () {
  var Hello, x;
  var get$ = Ember.get;
  Hello = Ember.Object.extend({
    message: Ember.computed(function () {
      return get$(this, 'prop1') + get$(this, 'prop2');
    }).property('prop1', 'prop2')
  });
  x = function () {
    return 'world';
  };
  x();
}.call(this);
//@ sourceMappingURL=helloworld.jsmap.json